// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEwT9N4BH6UEOPhJnZaTFMT3n_vZW8gg',
    appId: '1:741857275005:web:235e54d1a3573e76d81514',
    messagingSenderId: '741857275005',
    projectId: 'ai-powered-coach-2026',
    authDomain: 'ai-powered-coach-2026.firebaseapp.com',
    storageBucket: 'ai-powered-coach-2026.firebasestorage.app',
    measurementId: 'G-VTN53EEBJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEILKCYKMrCh4e0bZgcvE5_OOOkJXEbGM',
    appId: '1:741857275005:android:6a04d9e2207d7fc4d81514',
    messagingSenderId: '741857275005',
    projectId: 'ai-powered-coach-2026',
    storageBucket: 'ai-powered-coach-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0e7oOgvs2-Y_51f1CTrnj9WL5AD2Nbs',
    appId: '1:741857275005:ios:5e8e44b87e3e8636d81514',
    messagingSenderId: '741857275005',
    projectId: 'ai-powered-coach-2026',
    storageBucket: 'ai-powered-coach-2026.firebasestorage.app',
    iosBundleId: 'com.example.aiPoweredCoach2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0e7oOgvs2-Y_51f1CTrnj9WL5AD2Nbs',
    appId: '1:741857275005:ios:5e8e44b87e3e8636d81514',
    messagingSenderId: '741857275005',
    projectId: 'ai-powered-coach-2026',
    storageBucket: 'ai-powered-coach-2026.firebasestorage.app',
    iosBundleId: 'com.example.aiPoweredCoach2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEwT9N4BH6UEOPhJnZaTFMT3n_vZW8gg',
    appId: '1:741857275005:web:d3dcbf548f0232b5d81514',
    messagingSenderId: '741857275005',
    projectId: 'ai-powered-coach-2026',
    authDomain: 'ai-powered-coach-2026.firebaseapp.com',
    storageBucket: 'ai-powered-coach-2026.firebasestorage.app',
    measurementId: 'G-0H8NRL2FZD',
  );
}
